# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1aa8f96f20de3ba7838fee864bae97a4edd9fc03e45c2c2c1aaaddcb2d6e40dadf9bb06ce4037d5dea86ebd46939842bb971c1ac40174288fd7f881a164750e9

test:
  secret_key_base: 8414674d6329d9b715c9a2d7275f89b7c3ca27730634a6b236e858c276721b9f95dbce4efa525642e141dd29da6b066c86e8faad4b3e82f92882f6614b2c4261

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
